repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.81.0"
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      # - id: terraform_validate
      - id: terraform_tfsec
        args:
          - --args=--minimum-severity HIGH
      - id: terrascan
        args:
          - --args=--severity HIGH
          # List modules directories
          - --args=-d ./networking
      - id: terraform_docs
        args:
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
